In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [2]:
import requests_cache


requests_cache.install_cache(
    'forever_cache_0999',
    expire_after=None,         
    cache_control=False      
)

In [3]:
API_KEY = "f9479ced4d7be2f52fc2fe30a1206f67"
url = f"http://api.scraperapi.com?api_key={API_KEY}&url=https://www.espncricinfo.com/records/season/team-match-results/2024-2024?trophy=89"
response = requests.get(url)
print(response)

<CachedResponse [200]: "created: 2025-04-07 18:49:28 India Standard Time, expires: N/A (fresh), size: 344.96 KiB, request: GET http://api.scraperapi.com/?api_key=REDACTED&url=https%3A%2F%2Fwww.espncricinfo.com%2Frecords%2Fseason%2Fteam-match-results%2F2024-2024%3Ftrophy%3D89>

In [4]:
soup=BeautifulSoup(response.content,'lxml')

In [5]:
table = soup.find("table", class_="ds-w-full ds-table ds-table-xs ds-table-auto ds-w-full ds-overflow-scroll ds-scrollbar-hide")
print(table)

<table class="ds-w-full ds-table ds-table-xs ds-table-auto ds-w-full ds-overflow-scroll ds-scrollbar-hide"><thead class="ds-bg-fill-content-alternate ds-text-left"><tr class=""><td class="ds-min-w-max"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Team 1</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Team 2</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Winner</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Margin</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Ground</span></div></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Match Date</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Scorecard</span></div></td></tr></thead><tbody class=""><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">7 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/kensington-oval-bridgetown-barbados-59429" title="Bridgetown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Bridgetown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 29, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/india-vs-south-africa-final-1415755/full-scorecard" title="T20I # 2729"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2729</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">68 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/providence-stadium-guyana-208544" title="Providence"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Providence</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 27, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/england-vs-india-2nd-semi-final-1415754/full-scorecard" title="T20I # 2724"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2724</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">9 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/brian-lara-stadium-tarouba-trinidad-247418" title="Tarouba"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Tarouba</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 26, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/afghanistan-vs-south-africa-1st-semi-final-1415753/full-scorecard" title="T20I # 2723"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2723</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">Bangladesh</span></td><td class="ds-min-w-max ds-text-right"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">8 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/arnos-vale-ground-kingstown-st-vincent-59463" title="Kingstown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Kingstown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 24, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/afghanistan-vs-bangladesh-52nd-match-super-eights-group-1-1415752/full-scorecard" title="T20I # 2722"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2722</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Australia</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">24 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/daren-sammy-national-cricket-stadium-gros-islet-st-lucia-59518" title="Gros Islet"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Gros Islet</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 24, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/australia-vs-india-51st-match-super-eights-group-1-1415751/full-scorecard" title="T20I # 2721"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2721</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">3 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/sir-vivian-richards-stadium-north-sound-antigua-208543" title="North Sound"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">North Sound</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 23, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/west-indies-vs-south-africa-50th-match-super-eights-group-2-1415750/full-scorecard" title="T20I # 2720"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2720</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">U.S.A.</span></td><td class="ds-min-w-max ds-text-right"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">10 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/kensington-oval-bridgetown-barbados-59429" title="Bridgetown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Bridgetown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 23, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/england-vs-united-states-of-america-49th-match-super-eights-group-2-1415749/full-scorecard" title="T20I # 2719"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2719</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">Australia</span></td><td class="ds-min-w-max ds-text-right"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">21 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/arnos-vale-ground-kingstown-st-vincent-59463" title="Kingstown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Kingstown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 22, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/afghanistan-vs-australia-48th-match-super-eights-group-1-1415748/full-scorecard" title="T20I # 2717"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2717</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Bangladesh</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">50 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/sir-vivian-richards-stadium-north-sound-antigua-208543" title="North Sound"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">North Sound</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 22, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/bangladesh-vs-india-47th-match-super-eights-group-1-1415747/full-scorecard" title="T20I # 2716"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2716</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">U.S.A.</span></td><td class="ds-min-w-max ds-text-right"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">9 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/kensington-oval-bridgetown-barbados-59429" title="Bridgetown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Bridgetown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 21, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/west-indies-vs-united-states-of-america-46th-match-super-eights-group-2-1415746/full-scorecard" title="T20I # 2713"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2713</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">7 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/daren-sammy-national-cricket-stadium-gros-islet-st-lucia-59518" title="Gros Islet"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Gros Islet</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 21, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/england-vs-south-africa-45th-match-super-eights-group-2-1415745/full-scorecard" title="T20I # 2712"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2712</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">Australia</span></td><td class="ds-min-w-max ds-text-right"><span class="">Bangladesh</span></td><td class="ds-min-w-max ds-text-right"><span class="">Australia</span></td><td class="ds-min-w-max ds-text-right"><span class="">28 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/sir-vivian-richards-stadium-north-sound-antigua-208543" title="North Sound"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">North Sound</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 20, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/australia-vs-bangladesh-44th-match-super-eights-group-1-1415744/full-scorecard" title="T20I # 2711"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2711</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">47 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/kensington-oval-bridgetown-barbados-59429" title="Bridgetown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Bridgetown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 20, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/afghanistan-vs-india-43rd-match-super-eights-group-1-1415743/full-scorecard" title="T20I # 2710"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2710</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">8 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/daren-sammy-national-cricket-stadium-gros-islet-st-lucia-59518" title="Gros Islet"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Gros Islet</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 19, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/west-indies-vs-england-42nd-match-super-eights-group-2-1415742/full-scorecard" title="T20I # 2709"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2709</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">U.S.A.</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">18 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/sir-vivian-richards-stadium-north-sound-antigua-208543" title="North Sound"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">North Sound</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 19, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/south-africa-vs-united-states-of-america-41st-match-super-eights-group-2-1415741/full-scorecard" title="T20I # 2708"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2708</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">104 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/daren-sammy-national-cricket-stadium-gros-islet-st-lucia-59518" title="Gros Islet"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Gros Islet</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 17, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/west-indies-vs-afghanistan-40th-match-group-c-1415740/full-scorecard" title="T20I # 2703"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2703</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">New Zealand</span></td><td class="ds-min-w-max ds-text-right"><span class="">P.N.G.</span></td><td class="ds-min-w-max ds-text-right"><span class="">New Zealand</span></td><td class="ds-min-w-max ds-text-right"><span

In [6]:
thead = soup.find("thead") # ,class_="ds-bg-fill-content-alternate ds-text-left")
thead

<thead class="ds-bg-fill-content-alternate ds-text-left"><tr class=""><td class="ds-min-w-max"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Team 1</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Team 2</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Winner</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Margin</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Ground</span></div></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Match Date</span></div></td><td class="ds-min-w-max ds-text-right"><div class="ds-popper-wrapper"><span class="ds-cursor-pointer">Scorecard</span></div></td></tr></thead>

In [7]:
headers = [span.text.strip() for span in thead.find_all("span")]
print(headers)

['Team 1', 'Team 2', 'Winner', 'Margin', 'Ground', 'Match Date', 'Scorecard']

In [8]:
tbody=soup.find("tbody")
tbody

<tbody class=""><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">7 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/kensington-oval-bridgetown-barbados-59429" title="Bridgetown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Bridgetown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 29, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/india-vs-south-africa-final-1415755/full-scorecard" title="T20I # 2729"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2729</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">68 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/providence-stadium-guyana-208544" title="Providence"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Providence</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 27, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/england-vs-india-2nd-semi-final-1415754/full-scorecard" title="T20I # 2724"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2724</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">9 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/brian-lara-stadium-tarouba-trinidad-247418" title="Tarouba"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Tarouba</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 26, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/afghanistan-vs-south-africa-1st-semi-final-1415753/full-scorecard" title="T20I # 2723"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2723</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">Bangladesh</span></td><td class="ds-min-w-max ds-text-right"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">8 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/arnos-vale-ground-kingstown-st-vincent-59463" title="Kingstown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Kingstown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 24, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/afghanistan-vs-bangladesh-52nd-match-super-eights-group-1-1415752/full-scorecard" title="T20I # 2722"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2722</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Australia</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">24 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/daren-sammy-national-cricket-stadium-gros-islet-st-lucia-59518" title="Gros Islet"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Gros Islet</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 24, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/australia-vs-india-51st-match-super-eights-group-1-1415751/full-scorecard" title="T20I # 2721"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2721</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">3 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/sir-vivian-richards-stadium-north-sound-antigua-208543" title="North Sound"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">North Sound</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 23, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/west-indies-vs-south-africa-50th-match-super-eights-group-2-1415750/full-scorecard" title="T20I # 2720"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2720</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">U.S.A.</span></td><td class="ds-min-w-max ds-text-right"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">10 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/kensington-oval-bridgetown-barbados-59429" title="Bridgetown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Bridgetown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 23, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/england-vs-united-states-of-america-49th-match-super-eights-group-2-1415749/full-scorecard" title="T20I # 2719"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2719</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">Australia</span></td><td class="ds-min-w-max ds-text-right"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">21 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/arnos-vale-ground-kingstown-st-vincent-59463" title="Kingstown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Kingstown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 22, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/afghanistan-vs-australia-48th-match-super-eights-group-1-1415748/full-scorecard" title="T20I # 2717"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2717</span></a></span></td></tr><tr class="ds-bg-ui-fill-translucent"><td class="ds-min-w-max"><span class="">Bangladesh</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">50 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/sir-vivian-richards-stadium-north-sound-antigua-208543" title="North Sound"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">North Sound</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 22, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/bangladesh-vs-india-47th-match-super-eights-group-1-1415747/full-scorecard" title="T20I # 2716"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2716</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">U.S.A.</span></td><td class="ds-min-w-max ds-text-right"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">9 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/kensington-oval-bridgetown-barbados-59429" title="Bridgetown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Bridgetown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 21, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/west-indies-vs-united-states-of-america-46th-match-super-eights-group-2-1415746/full-scorecard" title="T20I # 2713"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2713</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">7 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/daren-sammy-national-cricket-stadium-gros-islet-st-lucia-59518" title="Gros Islet"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Gros Islet</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 21, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/england-vs-south-africa-45th-match-super-eights-group-2-1415745/full-scorecard" title="T20I # 2712"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2712</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">Australia</span></td><td class="ds-min-w-max ds-text-right"><span class="">Bangladesh</span></td><td class="ds-min-w-max ds-text-right"><span class="">Australia</span></td><td class="ds-min-w-max ds-text-right"><span class="">28 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/sir-vivian-richards-stadium-north-sound-antigua-208543" title="North Sound"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">North Sound</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 20, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/australia-vs-bangladesh-44th-match-super-eights-group-1-1415744/full-scorecard" title="T20I # 2711"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2711</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">India</span></td><td class="ds-min-w-max ds-text-right"><span class="">47 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/kensington-oval-bridgetown-barbados-59429" title="Bridgetown"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Bridgetown</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 20, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/afghanistan-vs-india-43rd-match-super-eights-group-1-1415743/full-scorecard" title="T20I # 2710"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2710</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">England</span></td><td class="ds-min-w-max ds-text-right"><span class="">8 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/daren-sammy-national-cricket-stadium-gros-islet-st-lucia-59518" title="Gros Islet"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Gros Islet</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 19, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/west-indies-vs-england-42nd-match-super-eights-group-2-1415742/full-scorecard" title="T20I # 2709"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2709</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">U.S.A.</span></td><td class="ds-min-w-max ds-text-right"><span class="">South Africa</span></td><td class="ds-min-w-max ds-text-right"><span class="">18 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/sir-vivian-richards-stadium-north-sound-antigua-208543" title="North Sound"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">North Sound</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 19, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/south-africa-vs-united-states-of-america-41st-match-super-eights-group-2-1415741/full-scorecard" title="T20I # 2708"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2708</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">Afghanistan</span></td><td class="ds-min-w-max ds-text-right"><span class="">West Indies</span></td><td class="ds-min-w-max ds-text-right"><span class="">104 runs</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/daren-sammy-national-cricket-stadium-gros-islet-st-lucia-59518" title="Gros Islet"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Gros Islet</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 17, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/west-indies-vs-afghanistan-40th-match-group-c-1415740/full-scorecard" title="T20I # 2703"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2703</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">New Zealand</span></td><td class="ds-min-w-max ds-text-right"><span class="">P.N.G.</span></td><td class="ds-min-w-max ds-text-right"><span class="">New Zealand</span></td><td class="ds-min-w-max ds-text-right"><span class="">7 wickets</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/cricket-grounds/brian-lara-stadium-tarouba-trinidad-247418" title="Tarouba"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">Tarouba</span></a></span></td><td class="ds-min-w-max ds-text-right ds-whitespace-nowrap"><span class="">Jun 17, 2024</span></td><td class="ds-min-w-max ds-text-right"><span class=""><a class="ds-inline-flex ds-items-start ds-leading-none" href="/series/icc-men-s-t20-world-cup-2024-1411166/new-zealand-vs-papua-new-guinea-39th-match-group-c-1415739/full-scorecard" title="T20I # 2702"><span class="ds-text-tight-s ds-font-regular ds-text-typo-primary hover:ds-text-typo-primary-hover ds-block">T20I # 2702</span></a></span></td></tr><tr class=""><td class="ds-min-w-max"><span class="">Netherlands</span></td><td class="ds-min-w-max ds-text-right"><span class="">Sri Lanka</span></td><td class="ds-min-w-max ds-text-right"><span class="">Sri Lanka</sp

In [9]:
rows=[]
for tr in tbody.find_all("tr"):
    cells=[td.text.strip() for td in tr.find_all("td")]
    rows.append(cells)
rows=rows[::-1]
rows

[['U.S.A.',
  'Canada',
  'U.S.A.',
  '7 wickets',
  'Dallas',
  'Jun 1, 2024',
  'T20I # 2632'],
 ['West Indies',
  'P.N.G.',
  'West Indies',
  '5 wickets',
  'Providence',
  'Jun 2, 2024',
  'T20I # 2633'],
 ['Namibia', 'Oman', 'tied', '-', 'Bridgetown', 'Jun 2, 2024', 'T20I # 2634'],
 ['South Africa',
  'Sri Lanka',
  'South Africa',
  '6 wickets',
  'New York',
  'Jun 3, 2024',
  'T20I # 2635'],
 ['Afghanistan',
  'Uganda',
  'Afghanistan',
  '125 runs',
  'Providence',
  'Jun 3, 2024',
  'T20I # 2636'],
 ['England',
  'Scotland',
  'no result',
  '-',
  'Bridgetown',
  'Jun 4, 2024',
  'T20I # 2637'],
 ['Nepal',
  'Netherlands',
  'Netherlands',
  '6 wickets',
  'Dallas',
  'Jun 4, 2024',
  'T20I # 2638'],
 ['India',
  'Ireland',
  'India',
  '8 wickets',
  'New York',
  'Jun 5, 2024',
  'T20I # 2639'],
 ['P.N.G.',
  'Uganda',
  'Uganda',
  '3 wickets',
  'Providence',
  'Jun 5, 2024',
  'T20I # 2640'],
 ['Australia',
  'Oman',
  'Australia',
  '39 runs',
  'Bridgetown',
  'Jun 5, 2024',
  'T20I # 2641'],
 ['U.S.A.', 'Pakistan', 'tied', '-', 'Dallas', 'Jun 6, 2024', 'T20I # 2642'],
 ['Namibia',
  'Scotland',
  'Scotland',
  '5 wickets',
  'Bridgetown',
  'Jun 6, 2024',
  'T20I # 2643'],
 ['Canada',
  'Ireland',
  'Canada',
  '12 runs',
  'New York',
  'Jun 7, 2024',
  'T20I # 2644'],
 ['Afghanistan',
  'New Zealand',
  'Afghanistan',
  '84 runs',
  'Providence',
  'Jun 7, 2024',
  'T20I # 2645'],
 ['Bangladesh',
  'Sri Lanka',
  'Bangladesh',
  '2 wickets',
  'Dallas',
  'Jun 7, 2024',
  'T20I # 2646'],
 ['Netherlands',
  'South Africa',
  'South Africa',
  '4 wickets',
  'New York',
  'Jun 8, 2024',
  'T20I # 2649'],
 ['Australia',
  'England',
  'Australia',
  '36 runs',
  'Bridgetown',
  'Jun 8, 2024',
  'T20I # 2650'],
 ['West Indies',
  'Uganda',
  'West Indies',
  '134 runs',
  'Providence',
  'Jun 8, 2024',
  'T20I # 2651'],
 ['India',
  'Pakistan',
  'India',
  '6 runs',
  'New York',
  'Jun 9, 2024',
  'T20I # 2658'],
 ['Oman',
  'Scotland',
  'Scotland',
  '7 wickets',
  'North Sound',
  'Jun 9, 2024',
  'T20I # 2659'],
 ['Bangladesh',
  'South Africa',
  'South Africa',
  '4 runs',
  'New York',
  'Jun 10, 2024',
  'T20I # 2664'],
 ['Canada',
  'Pakistan',
  'Pakistan',
  '7 wickets',
  'New York',
  'Jun 11, 2024',
  'T20I # 2665'],
 ['Australia',
  'Namibia',
  'Australia',
  '9 wickets',
  'North Sound',
  'Jun 11, 2024',
  'T20I # 2666'],
 ['U.S.A.',
  'India',
  'India',
  '7 wickets',
  'New York',
  'Jun 12, 2024',
  'T20I # 2671'],
 ['West Indies',
  'New Zealand',
  'West Indies',
  '13 runs',
  'Tarouba',
  'Jun 12, 2024',
  'T20I # 2672'],
 ['Bangladesh',
  'Netherlands',
  'Bangladesh',
  '25 runs',
  'Kingstown',
  'Jun 13, 2024',
  'T20I # 2677'],
 ['England',
  'Oman',
  'England',
  '8 wickets',
  'North Sound',
  'Jun 13, 2024',
  'T20I # 2678'],
 ['Afghanistan',
  'P.N.G.',
  'Afghanistan',
  '7 wickets',
  'Tarouba',
  'Jun 13, 2024',
  'T20I # 2679'],
 ['Nepal',
  'South Africa',
  'South Africa',
  '1 run',
  'Kingstown',
  'Jun 14, 2024',
  'T20I # 2681'],
 ['New Zealand',
  'Uganda',
  'New Zealand',
  '9 wickets',
  'Tarouba',
  'Jun 14, 2024',
  'T20I # 2682'],
 ['England',
  'Namibia',
  'England',
  '41 runs',
  'North Sound',
  'Jun 15, 2024',
  'T20I # 2688'],
 ['Australia',
  'Scotland',
  'Australia',
  '5 wickets',
  'Gros Islet',
  'Jun 15, 2024',
  'T20I # 2689'],
 ['Ireland',
  'Pakistan',
  'Pakistan',
  '3 wickets',
  'Lauderhill',
  'Jun 16, 2024',
  'T20I # 2697'],
 ['Bangladesh',
  'Nepal',
  'Bangladesh',
  '21 runs',
  'Kingstown',
  'Jun 16, 2024',
  'T20I # 2698'],
 ['Netherlands',
  'Sri Lanka',
  'Sri Lanka',
  '83 runs',
  'Gros Islet',
  'Jun 16, 2024',
  'T20I # 2699'],
 ['New Zealand',
  'P.N.G.',
  'New Zealand',
  '7 wickets',
  'Tarouba',
  'Jun 17, 2024',
  'T20I # 2702'],
 ['West Indies',
  'Afghanistan',
  'West Indies',
  '104 runs',
  'Gros Islet',
  'Jun 17, 2024',
  'T20I # 2703'],
 ['South Africa',
  'U.S.A.',
  'South Africa',
  '18 runs',
  'North Sound',
  'Jun 19, 2024',
  'T20I # 2708'],
 ['West Indies',
  'England',
  'England',
  '8 wickets',
  'Gros Islet',
  'Jun 19, 2024',
  'T20I # 2709'],
 ['Afghanistan',
  'India',
  'India',
  '47 runs',
  'Bridgetown',
  'Jun 20, 2024',
  'T20I # 2710'],
 ['Australia',
  'Bangladesh',
  'Australia',
  '28 runs',
  'North Sound',
  'Jun 20, 2024',
  'T20I # 2711'],
 ['England',
  'South Africa',
  'South Africa',
  '7 runs',
  'Gros Islet',
  'Jun 21, 2024',
  'T20I # 2712'],
 ['West Indies',
  'U.S.A.',
  'West Indies',
  '9 wickets',
  'Bridgetown',
  'Jun 21, 2024',
  'T20I # 2713'],
 ['Bangladesh',
  'India',
  'India',
  '50 runs',
  'North Sound',
  'Jun 22, 2024',
  'T20I # 2716'],
 ['Afghanistan',
  'Australia',
  'Afghanistan',
  '21 runs',
  'Kingstown',
  'Jun 22, 2024',
  'T20I # 2717'],
 ['England',
  'U.S.A.',
  'England',
  '10 wickets',
  'Bridgetown',
  'Jun 23, 2024',
  'T20I # 2719'],
 ['West Indies',
  'South Africa',
  'South Africa',
  '3 wickets',
  'North Sound',
  'Jun 23, 2024',
  'T20I # 2720'],
 ['Australia',
  'India',
  'India',
  '24 runs',
  'Gros Islet',
  'Jun 24, 2024',
  'T20I # 2721'],
 ['Afghanistan',
  'Bangladesh',
  'Afghanistan',
  '8 runs',
  'Kingstown',
  'Jun 24, 2024',
  'T20I # 2722'],
 ['Afghanistan',
  'South Africa',
  'South Africa',
  '9 wickets',
  'Tarouba',
  'Jun 26, 2024',
  'T20I # 2723'],
 ['England',
  'India',
  'India',
  '68 runs',
  'Providence',
  'Jun 27, 2024',
  'T20I # 2724'],
 ['India',
  'South Africa',
  'India',
  '7 runs',
  'Bridgetown',
  'Jun 29, 2024',
  'T20I # 2729']]

In [10]:
df_match=pd.DataFrame(rows,columns=headers)
df_match

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Scorecard
0,U.S.A.,Canada,U.S.A.,7 wickets,Dallas,"Jun 1, 2024",T20I # 2632
1,West Indies,P.N.G.,West Indies,5 wickets,Providence,"Jun 2, 2024",T20I # 2633
2,Namibia,Oman,tied,-,Bridgetown,"Jun 2, 2024",T20I # 2634
3,South Africa,Sri Lanka,South Africa,6 wickets,New York,"Jun 3, 2024",T20I # 2635
4,Afghanistan,Uganda,Afghanistan,125 runs,Providence,"Jun 3, 2024",T20I # 2636
5,England,Scotland,no result,-,Bridgetown,"Jun 4, 2024",T20I # 2637
6,Nepal,Netherlands,Netherlands,6 wickets,Dallas,"Jun 4, 2024",T20I # 2638
7,India,Ireland,India,8 wickets,New York,"Jun 5, 2024",T20I # 2639
8,P.N.G.,Uganda,Uganda,3 wickets,Providence,"Jun 5, 2024",T20I # 2640
9,Australia,Oman,Australia,39 runs,Bridgetown,"Jun 5, 2024",T20I # 2641
10,U.S.A.,Pakistan,tied,-,Dallas,"Jun 6, 2024",T20I # 2642
11,Namibia,Scotland,Scotland,5 wickets,Bridgetown,"Jun 6, 2024",T20I # 2643
12,Canada,Ireland,Canada,12 runs,New York,"Jun 7, 2024",T20I # 2644
13,Afghanistan,New Zealand,Afghanistan,84 runs,Providence,"Jun 7, 2024",T20I # 2645
14,Bangladesh,Sri Lanka,Bangladesh,2 wickets,Dallas,"Jun 7, 2024",T20I # 2646
15,Netherlands,South Africa,South Africa,4 wickets,New York,"Jun 8, 2024",T20I # 2649
16,Australia,England,Australia,36 runs,Bridgetown,"Jun 8, 2024",T20I # 2650
17,West Indies,Uganda,West Indies,134 runs,Providence,"Jun 8, 2024",T20I # 2651
18,India,Pakistan,India,6 runs,New York,"Jun 9, 2024",T20I # 2658
19,Oman,Scotland,Scotland,7 wickets,North Sound,"Jun 9, 2024",T20I # 2659
20,Bangladesh,South Africa,South Africa,4 runs,New York,"Jun 10, 2024",T20I # 2664
21,Canada,Pakistan,Pakistan,7 wickets,New York,"Jun 11, 2024",T20I # 2665
22,Australia,Namibia,Australia,9 wickets,North Sound,"Jun 11, 2024",T20I # 2666
23,U.S.A.,India,India,7 wickets,New York,"Jun 12, 2024",T20I # 2671
24,West Indies,New Zealand,West Indies,13 runs,Tarouba,"Jun 12, 2024",T20I # 2672
25,Bangladesh,Netherlands,Bangladesh,25 runs,Kingstown,"Jun 13, 2024",T20I # 2677
26,England,Oman,England,8 wickets,North Sound,"Jun 13, 2024",T20I # 2678
27,Afghanistan,P.N.G.,Afghanistan,7 wickets,Tarouba,"Jun 13, 2024",T20I # 2679
28,Nepal,South Africa,South Africa,1 run,Kingstown,"Jun 14, 2024",T20I # 2681
29,New Zealand,Uganda,New Zealand,9 wickets,Tarouba,"Jun 14, 2024",T20I # 2682
30,England,Namibia,England,41 runs,North Sound,"Jun 15, 2024",T20I # 2688
31,Australia,Scotland,Australia,5 wickets,Gros Islet,"Jun 15, 2024",T20I # 2689
32,Ireland,Pakistan,Pakistan,3 wickets,Lauderhill,"Jun 16, 2024",T20I # 2697
33,Bangladesh,Nepal,Bangladesh,21 runs,Kingstown,"Jun 16, 2024",T20I # 2698
34,Netherlands,Sri Lanka,Sri Lanka,83 runs,Gros Islet,"Jun 16, 2024",T20I # 2699
35,New Zealand,P.N.G.,New Zealand,7 wickets,Tarouba,"Jun 17, 2024",T20I # 2702
36,West Indies,Afghanistan,West Indies,104 runs,Gros Islet,"Jun 17, 2024",T20I # 2703
37,South Africa,U.S.A.,South Africa,18 runs,North Sound,"Jun 19, 2024",T20I # 2708
38,West Indies,England,England,8 wickets,Gros Islet,"Jun 19, 2024",T20I # 2709
39,Afghanistan,India,India,47 runs,Bridgetown,"Jun 20, 2024",T20I # 2710
40,Australia,Bangladesh,Australia,28 runs,North Sound,"Jun 20, 2024",T20I # 2711
41,England,South Africa,South Africa,7 runs,Gros Islet,"Jun 21, 2024",T20I # 2712
42,West Indies,U.S.A.,West Indies,9 wickets,Bridgetown,"Jun 21, 2024",T20I # 2713
43,Bangladesh,India,India,50 runs,North Sound,"Jun 22, 2024",T20I # 2716
44,Afghanistan,Australia,Afghanistan,21 runs,Kingstown,"Jun 22, 2024",T20I # 2717
45,England,U.S.A.,England,10 wickets,Bridgetown,"Jun 23, 2024",T20I # 2719
46,West Indies,South Africa,South Africa,3 wickets,North Sound,"Jun 23, 2024",T20I # 2720
47,Australia,India,India,24 runs,Gros Islet,"Jun 24, 2024",T20I # 2721
48,Afghanistan,Bangladesh,Afghanistan,8 runs,Kingstown,"Jun 24, 2024",T20I # 2722
49,Afghanistan,South Africa,South Africa,9 wickets,Tarouba,"Jun 26, 2024",T20I # 2723
50,England,India,India,68 runs,Providence,"Jun 27, 2024",T20I # 2724
51,India,South Africa,India,7 runs,Bridgetown,"Jun 29, 2024",T20I # 2729

In [11]:
df_match.rename({'Scorecard':'Match_id'},axis=1,inplace=True)
df_match

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Match_id
0,U.S.A.,Canada,U.S.A.,7 wickets,Dallas,"Jun 1, 2024",T20I # 2632
1,West Indies,P.N.G.,West Indies,5 wickets,Providence,"Jun 2, 2024",T20I # 2633
2,Namibia,Oman,tied,-,Bridgetown,"Jun 2, 2024",T20I # 2634
3,South Africa,Sri Lanka,South Africa,6 wickets,New York,"Jun 3, 2024",T20I # 2635
4,Afghanistan,Uganda,Afghanistan,125 runs,Providence,"Jun 3, 2024",T20I # 2636
5,England,Scotland,no result,-,Bridgetown,"Jun 4, 2024",T20I # 2637
6,Nepal,Netherlands,Netherlands,6 wickets,Dallas,"Jun 4, 2024",T20I # 2638
7,India,Ireland,India,8 wickets,New York,"Jun 5, 2024",T20I # 2639
8,P.N.G.,Uganda,Uganda,3 wickets,Providence,"Jun 5, 2024",T20I # 2640
9,Australia,Oman,Australia,39 runs,Bridgetown,"Jun 5, 2024",T20I # 2641
10,U.S.A.,Pakistan,tied,-,Dallas,"Jun 6, 2024",T20I # 2642
11,Namibia,Scotland,Scotland,5 wickets,Bridgetown,"Jun 6, 2024",T20I # 2643
12,Canada,Ireland,Canada,12 runs,New York,"Jun 7, 2024",T20I # 2644
13,Afghanistan,New Zealand,Afghanistan,84 runs,Providence,"Jun 7, 2024",T20I # 2645
14,Bangladesh,Sri Lanka,Bangladesh,2 wickets,Dallas,"Jun 7, 2024",T20I # 2646
15,Netherlands,South Africa,South Africa,4 wickets,New York,"Jun 8, 2024",T20I # 2649
16,Australia,England,Australia,36 runs,Bridgetown,"Jun 8, 2024",T20I # 2650
17,West Indies,Uganda,West Indies,134 runs,Providence,"Jun 8, 2024",T20I # 2651
18,India,Pakistan,India,6 runs,New York,"Jun 9, 2024",T20I # 2658
19,Oman,Scotland,Scotland,7 wickets,North Sound,"Jun 9, 2024",T20I # 2659
20,Bangladesh,South Africa,South Africa,4 runs,New York,"Jun 10, 2024",T20I # 2664
21,Canada,Pakistan,Pakistan,7 wickets,New York,"Jun 11, 2024",T20I # 2665
22,Australia,Namibia,Australia,9 wickets,North Sound,"Jun 11, 2024",T20I # 2666
23,U.S.A.,India,India,7 wickets,New York,"Jun 12, 2024",T20I # 2671
24,West Indies,New Zealand,West Indies,13 runs,Tarouba,"Jun 12, 2024",T20I # 2672
25,Bangladesh,Netherlands,Bangladesh,25 runs,Kingstown,"Jun 13, 2024",T20I # 2677
26,England,Oman,England,8 wickets,North Sound,"Jun 13, 2024",T20I # 2678
27,Afghanistan,P.N.G.,Afghanistan,7 wickets,Tarouba,"Jun 13, 2024",T20I # 2679
28,Nepal,South Africa,South Africa,1 run,Kingstown,"Jun 14, 2024",T20I # 2681
29,New Zealand,Uganda,New Zealand,9 wickets,Tarouba,"Jun 14, 2024",T20I # 2682
30,England,Namibia,England,41 runs,North Sound,"Jun 15, 2024",T20I # 2688
31,Australia,Scotland,Australia,5 wickets,Gros Islet,"Jun 15, 2024",T20I # 2689
32,Ireland,Pakistan,Pakistan,3 wickets,Lauderhill,"Jun 16, 2024",T20I # 2697
33,Bangladesh,Nepal,Bangladesh,21 runs,Kingstown,"Jun 16, 2024",T20I # 2698
34,Netherlands,Sri Lanka,Sri Lanka,83 runs,Gros Islet,"Jun 16, 2024",T20I # 2699
35,New Zealand,P.N.G.,New Zealand,7 wickets,Tarouba,"Jun 17, 2024",T20I # 2702
36,West Indies,Afghanistan,West Indies,104 runs,Gros Islet,"Jun 17, 2024",T20I # 2703
37,South Africa,U.S.A.,South Africa,18 runs,North Sound,"Jun 19, 2024",T20I # 2708
38,West Indies,England,England,8 wickets,Gros Islet,"Jun 19, 2024",T20I # 2709
39,Afghanistan,India,India,47 runs,Bridgetown,"Jun 20, 2024",T20I # 2710
40,Australia,Bangladesh,Australia,28 runs,North Sound,"Jun 20, 2024",T20I # 2711
41,England,South Africa,South Africa,7 runs,Gros Islet,"Jun 21, 2024",T20I # 2712
42,West Indies,U.S.A.,West Indies,9 wickets,Bridgetown,"Jun 21, 2024",T20I # 2713
43,Bangladesh,India,India,50 runs,North Sound,"Jun 22, 2024",T20I # 2716
44,Afghanistan,Australia,Afghanistan,21 runs,Kingstown,"Jun 22, 2024",T20I # 2717
45,England,U.S.A.,England,10 wickets,Bridgetown,"Jun 23, 2024",T20I # 2719
46,West Indies,South Africa,South Africa,3 wickets,North Sound,"Jun 23, 2024",T20I # 2720
47,Australia,India,India,24 runs,Gros Islet,"Jun 24, 2024",T20I # 2721
48,Afghanistan,Bangladesh,Afghanistan,8 runs,Kingstown,"Jun 24, 2024",T20I # 2722
49,Afghanistan,South Africa,South Africa,9 wickets,Tarouba,"Jun 26, 2024",T20I # 2723
50,England,India,India,68 runs,Providence,"Jun 27, 2024",T20I # 2724
51,India,South Africa,India,7 runs,Bridgetown,"Jun 29, 2024",T20I # 2729

In [12]:
team_name_mapping = {
    'U.S.A.': 'United States of America',
    'P.N.G.': 'Papua New Guinea'
}

df_match.replace(team_name_mapping, inplace=True)
df_match

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Match_id
0,United States of America,Canada,United States of America,7 wickets,Dallas,"Jun 1, 2024",T20I # 2632
1,West Indies,Papua New Guinea,West Indies,5 wickets,Providence,"Jun 2, 2024",T20I # 2633
2,Namibia,Oman,tied,-,Bridgetown,"Jun 2, 2024",T20I # 2634
3,South Africa,Sri Lanka,South Africa,6 wickets,New York,"Jun 3, 2024",T20I # 2635
4,Afghanistan,Uganda,Afghanistan,125 runs,Providence,"Jun 3, 2024",T20I # 2636
5,England,Scotland,no result,-,Bridgetown,"Jun 4, 2024",T20I # 2637
6,Nepal,Netherlands,Netherlands,6 wickets,Dallas,"Jun 4, 2024",T20I # 2638
7,India,Ireland,India,8 wickets,New York,"Jun 5, 2024",T20I # 2639
8,Papua New Guinea,Uganda,Uganda,3 wickets,Providence,"Jun 5, 2024",T20I # 2640
9,Australia,Oman,Australia,39 runs,Bridgetown,"Jun 5, 2024",T20I # 2641
10,United States of America,Pakistan,tied,-,Dallas,"Jun 6, 2024",T20I # 2642
11,Namibia,Scotland,Scotland,5 wickets,Bridgetown,"Jun 6, 2024",T20I # 2643
12,Canada,Ireland,Canada,12 runs,New York,"Jun 7, 2024",T20I # 2644
13,Afghanistan,New Zealand,Afghanistan,84 runs,Providence,"Jun 7, 2024",T20I # 2645
14,Bangladesh,Sri Lanka,Bangladesh,2 wickets,Dallas,"Jun 7, 2024",T20I # 2646
15,Netherlands,South Africa,South Africa,4 wickets,New York,"Jun 8, 2024",T20I # 2649
16,Australia,England,Australia,36 runs,Bridgetown,"Jun 8, 2024",T20I # 2650
17,West Indies,Uganda,West Indies,134 runs,Providence,"Jun 8, 2024",T20I # 2651
18,India,Pakistan,India,6 runs,New York,"Jun 9, 2024",T20I # 2658
19,Oman,Scotland,Scotland,7 wickets,North Sound,"Jun 9, 2024",T20I # 2659
20,Bangladesh,South Africa,South Africa,4 runs,New York,"Jun 10, 2024",T20I # 2664
21,Canada,Pakistan,Pakistan,7 wickets,New York,"Jun 11, 2024",T20I # 2665
22,Australia,Namibia,Australia,9 wickets,North Sound,"Jun 11, 2024",T20I # 2666
23,United States of America,India,India,7 wickets,New York,"Jun 12, 2024",T20I # 2671
24,West Indies,New Zealand,West Indies,13 runs,Tarouba,"Jun 12, 2024",T20I # 2672
25,Bangladesh,Netherlands,Bangladesh,25 runs,Kingstown,"Jun 13, 2024",T20I # 2677
26,England,Oman,England,8 wickets,North Sound,"Jun 13, 2024",T20I # 2678
27,Afghanistan,Papua New Guinea,Afghanistan,7 wickets,Tarouba,"Jun 13, 2024",T20I # 2679
28,Nepal,South Africa,South Africa,1 run,Kingstown,"Jun 14, 2024",T20I # 2681
29,New Zealand,Uganda,New Zealand,9 wickets,Tarouba,"Jun 14, 2024",T20I # 2682
30,England,Namibia,England,41 runs,North Sound,"Jun 15, 2024",T20I # 2688
31,Australia,Scotland,Australia,5 wickets,Gros Islet,"Jun 15, 2024",T20I # 2689
32,Ireland,Pakistan,Pakistan,3 wickets,Lauderhill,"Jun 16, 2024",T20I # 2697
33,Bangladesh,Nepal,Bangladesh,21 runs,Kingstown,"Jun 16, 2024",T20I # 2698
34,Netherlands,Sri Lanka,Sri Lanka,83 runs,Gros Islet,"Jun 16, 2024",T20I # 2699
35,New Zealand,Papua New Guinea,New Zealand,7 wickets,Tarouba,"Jun 17, 2024",T20I # 2702
36,West Indies,Afghanistan,West Indies,104 runs,Gros Islet,"Jun 17, 2024",T20I # 2703
37,South Africa,United States of America,South Africa,18 runs,North Sound,"Jun 19, 2024",T20I # 2708
38,West Indies,England,England,8 wickets,Gros Islet,"Jun 19, 2024",T20I # 2709
39,Afghanistan,India,India,47 runs,Bridgetown,"Jun 20, 2024",T20I # 2710
40,Australia,Bangladesh,Australia,28 runs,North Sound,"Jun 20, 2024",T20I # 2711
41,England,South Africa,South Africa,7 runs,Gros Islet,"Jun 21, 2024",T20I # 2712
42,West Indies,United States of America,West Indies,9 wickets,Bridgetown,"Jun 21, 2024",T20I # 2713
43,Bangladesh,India,India,50 runs,North Sound,"Jun 22, 2024",T20I # 2716
44,Afghanistan,Australia,Afghanistan,21 runs,Kingstown,"Jun 22, 2024",T20I # 2717
45,England,United States of America,England,10 wickets,Bridgetown,"Jun 23, 2024",T20I # 2719
46,West Indies,South Africa,South Africa,3 wickets,North Sound,"Jun 23, 2024",T20I # 2720
47,Australia,India,India,24 runs,Gros Islet,"Jun 24, 2024",T20I # 2721
48,Afghanistan,Bangladesh,Afghanistan,8 runs,Kingstown,"Jun 24, 2024",T20I # 2722
49,Afghanistan,South Africa,South Africa,9 wickets,Tarouba,"Jun 26, 2024",T20I # 2723
50,England,India,India,68 runs,Providence,"Jun 27, 2024",T20I # 2724
51,India,South Africa,India,7 runs,Bridgetown,"Jun 29, 2024",T20I # 2729

In [13]:
df_match.to_csv("t20 files_summary/dim_match_summary.csv",index=False)

In [14]:
match_ids_dict={}
for index,row in df_match.iterrows():
    key1 = row['Team 1'] + ' vs ' + row['Team 2']
    key2 = row['Team 2'] + ' vs ' + row['Team 1']

    match_ids_dict[key1]=row['Match_id']
    match_ids_dict[key2]=row['Match_id']
match_ids_dict

{'United States of America vs Canada': 'T20I # 2632',
 'Canada vs United States of America': 'T20I # 2632',
 'West Indies vs Papua New Guinea': 'T20I # 2633',
 'Papua New Guinea vs West Indies': 'T20I # 2633',
 'Namibia vs Oman': 'T20I # 2634',
 'Oman vs Namibia': 'T20I # 2634',
 'South Africa vs Sri Lanka': 'T20I # 2635',
 'Sri Lanka vs South Africa': 'T20I # 2635',
 'Afghanistan vs Uganda': 'T20I # 2636',
 'Uganda vs Afghanistan': 'T20I # 2636',
 'England vs Scotland': 'T20I # 2637',
 'Scotland vs England': 'T20I # 2637',
 'Nepal vs Netherlands': 'T20I # 2638',
 'Netherlands vs Nepal': 'T20I # 2638',
 'India vs Ireland': 'T20I # 2639',
 'Ireland vs India': 'T20I # 2639',
 'Papua New Guinea vs Uganda': 'T20I # 2640',
 'Uganda vs Papua New Guinea': 'T20I # 2640',
 'Australia vs Oman': 'T20I # 2641',
 'Oman vs Australia': 'T20I # 2641',
 'United States of America vs Pakistan': 'T20I # 2642',
 'Pakistan vs United States of America': 'T20I # 2642',
 'Namibia vs Scotland': 'T20I # 2643',
 'Scotland vs Namibia': 'T20I # 2643',
 'Canada vs Ireland': 'T20I # 2644',
 'Ireland vs Canada': 'T20I # 2644',
 'Afghanistan vs New Zealand': 'T20I # 2645',
 'New Zealand vs Afghanistan': 'T20I # 2645',
 'Bangladesh vs Sri Lanka': 'T20I # 2646',
 'Sri Lanka vs Bangladesh': 'T20I # 2646',
 'Netherlands vs South Africa': 'T20I # 2649',
 'South Africa vs Netherlands': 'T20I # 2649',
 'Australia vs England': 'T20I # 2650',
 'England vs Australia': 'T20I # 2650',
 'West Indies vs Uganda': 'T20I # 2651',
 'Uganda vs West Indies': 'T20I # 2651',
 'India vs Pakistan': 'T20I # 2658',
 'Pakistan vs India': 'T20I # 2658',
 'Oman vs Scotland': 'T20I # 2659',
 'Scotland vs Oman': 'T20I # 2659',
 'Bangladesh vs South Africa': 'T20I # 2664',
 'South Africa vs Bangladesh': 'T20I # 2664',
 'Canada vs Pakistan': 'T20I # 2665',
 'Pakistan vs Canada': 'T20I # 2665',
 'Australia vs Namibia': 'T20I # 2666',
 'Namibia vs Australia': 'T20I # 2666',
 'United States of America vs India': 'T20I # 2671',
 'India vs United States of America': 'T20I # 2671',
 'West Indies vs New Zealand': 'T20I # 2672',
 'New Zealand vs West Indies': 'T20I # 2672',
 'Bangladesh vs Netherlands': 'T20I # 2677',
 'Netherlands vs Bangladesh': 'T20I # 2677',
 'England vs Oman': 'T20I # 2678',
 'Oman vs England': 'T20I # 2678',
 'Afghanistan vs Papua New Guinea': 'T20I # 2679',
 'Papua New Guinea vs Afghanistan': 'T20I # 2679',
 'Nepal vs South Africa': 'T20I # 2681',
 'South Africa vs Nepal': 'T20I # 2681',
 'New Zealand vs Uganda': 'T20I # 2682',
 'Uganda vs New Zealand': 'T20I # 2682',
 'England vs Namibia': 'T20I # 2688',
 'Namibia vs England': 'T20I # 2688',
 'Australia vs Scotland': 'T20I # 2689',
 'Scotland vs Australia': 'T20I # 2689',
 'Ireland vs Pakistan': 'T20I # 2697',
 'Pakistan vs Ireland': 'T20I # 2697',
 'Bangladesh vs Nepal': 'T20I # 2698',
 'Nepal vs Bangladesh': 'T20I # 2698',
 'Netherlands vs Sri Lanka': 'T20I # 2699',
 'Sri Lanka vs Netherlands': 'T20I # 2699',
 'New Zealand vs Papua New Guinea': 'T20I # 2702',
 'Papua New Guinea vs New Zealand': 'T20I # 2702',
 'West Indies vs Afghanistan': 'T20I # 2703',
 'Afghanistan vs West Indies': 'T20I # 2703',
 'South Africa vs United States of America': 'T20I # 2708',
 'United States of America vs South Africa': 'T20I # 2708',
 'West Indies vs England': 'T20I # 2709',
 'England vs West Indies': 'T20I # 2709',
 'Afghanistan vs India': 'T20I # 2710',
 'India vs Afghanistan': 'T20I # 2710',
 'Australia vs Bangladesh': 'T20I # 2711',
 'Bangladesh vs Australia': 'T20I # 2711',
 'England vs South Africa': 'T20I # 2712',
 'South Africa vs England': 'T20I # 2712',
 'West Indies vs United States of America': 'T20I # 2713',
 'United States of America vs West Indies': 'T20I # 2713',
 'Bangladesh vs India': 'T20I # 2716',
 'India vs Bangladesh': 'T20I # 2716',
 'Afghanistan vs Australia': 'T20I # 2717',
 'Australia vs Afghanistan': 'T20I # 2717',
 'England vs United States of America': 'T20I # 2719',
 'United States of America vs England': 'T20I # 2719',
 'West Indies vs South Africa': 'T20I # 2720',
 'South Africa vs West Indies': 'T20I # 2720',
 'Australia vs India': 'T20I # 2721',
 'India vs Australia': 'T20I # 2721',
 'Afghanistan vs Bangladesh': 'T20I # 2722',
 'Bangladesh vs Afghanistan': 'T20I # 2722',
 'Afghanistan vs South Africa': 'T20I # 2723',
 'South Africa vs Afghanistan': 'T20I # 2723',
 'England vs India': 'T20I # 2724',
 'India vs England': 'T20I # 2724',
 'India vs South Africa': 'T20I # 2729',
 'South Africa vs India': 'T20I # 2729'}

In [15]:

columns = ["match", "team", "battingposition", "batsmanname", "dismissal", "runs", "balls", "fours", "sixes", "strikerate"]
data = []

def clean_text(text):
    text = re.sub(r'[^\x00-\x7F]+', '', text) 
    text = re.sub(r'\(.*?\)', '', text)  
    return text.strip()

# Iterate through the match IDs
for i in range(1415701, 1415756):
    API_KEY = "f9479ced4d7be2f52fc2fe30a1206f67"
    url = f"http://api.scraperapi.com?api_key={API_KEY}&url=https://www.espncricinfo.com/series/icc-men-s-t20-world-cup-2024-1411166/united-states-of-america-vs-canada-1st-match-group-a-{i}/full-scorecard"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36'}
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, "lxml")
        
        team_names = []
        innings = soup.find_all("div", class_="ds-rounded-lg ds-mt-2")
        
        for inning in innings:
            team_name_elem = inning.find("span", class_="ds-text-title-xs ds-font-bold ds-capitalize")
            if team_name_elem:
                team_names.append(team_name_elem.text.strip())
        
        # Check if we found valid team names
        if len(team_names) < 2:
            print(f"ABANDONED MATCH ID {i}")
            continue  
        
        match_title = f"{team_names[0]} vs {team_names[1]}"
        for inning in innings:
            team_name_elem = inning.find("span", class_="ds-text-title-xs ds-font-bold ds-capitalize")
            if team_name_elem:
                team_name = team_name_elem.text.strip()
                batting_table = inning.find("table", class_="ds-w-full ds-table ds-table-md ds-table-auto ci-scorecard-table")
                
                if batting_table:
                    rows = batting_table.find_all("tr")
                    batting_position = 1
                    for row in rows:
                        cols = row.find_all("td")
                        if len(cols) >= 7:
                            batsman_name = clean_text(cols[0].text.strip())
                            dismissal = cols[1].text.strip()
                            R = cols[2].text.strip()
                            B = cols[3].text.strip()
                            fours = cols[5].text.strip()
                            sixes = cols[6].text.strip()
                            SR = cols[7].text.strip()
                            
                            data.append([match_title, team_name, batting_position, batsman_name, dismissal, R, B, fours, sixes, SR])
                            batting_position += 1


df_batting = pd.DataFrame(data, columns=columns)


df_batting

ABANDONED MATCH ID 1415706
ABANDONED MATCH ID 1415723
ABANDONED MATCH ID 1415730
ABANDONED MATCH ID 1415733

,match,team,battingposition,batsmanname,dismissal,runs,balls,fours,sixes,strikerate
0,Canada vs United States of America,Canada,1,Aaron Johnson,c Kumar b Harmeet Singh,23,16,5,0,143.75
1,Canada vs United States of America,Canada,2,Navneet Dhaliwal,c Jasdeep Singh b Anderson,61,44,6,3,138.63
2,Canada vs United States of America,Canada,3,Pargat Singh,run out (Jasdeep Singh/†Patel),5,7,0,0,71.42
3,Canada vs United States of America,Canada,4,Nicholas Kirton,c Anderson b Ali Khan,51,31,3,2,164.51
4,Canada vs United States of America,Canada,5,Shreyas Movva,not out,32,16,2,2,200.00
...,...,...,...,...,...,...,...,...,...,...
845,India vs South Africa,South Africa,6,David Miller,c Yadav b Pandya,21,17,1,1,123.52
846,India vs South Africa,South Africa,7,Marco Jansen,b Bumrah,2,4,0,0,50.00
847,India vs South Africa,South Africa,8,Keshav Maharaj,not out,2,7,0,0,28.57
848,India vs South Africa,South Africa,9,Kagiso Rabada,c Yadav b Pandya,4,3,1,0,133.33
849,India vs South Africa,South Africa,10,Anrich Nortje,not out,1,1,0,0,100.00

In [16]:
df_batting["out/not_out"]=df_batting["dismissal"].apply(lambda x: "not out" if "not out" in x.lower() else "out")
df_batting

,match,team,battingposition,batsmanname,dismissal,runs,balls,fours,sixes,strikerate,out/not_out
0,Canada vs United States of America,Canada,1,Aaron Johnson,c Kumar b Harmeet Singh,23,16,5,0,143.75,out
1,Canada vs United States of America,Canada,2,Navneet Dhaliwal,c Jasdeep Singh b Anderson,61,44,6,3,138.63,out
2,Canada vs United States of America,Canada,3,Pargat Singh,run out (Jasdeep Singh/†Patel),5,7,0,0,71.42,out
3,Canada vs United States of America,Canada,4,Nicholas Kirton,c Anderson b Ali Khan,51,31,3,2,164.51,out
4,Canada vs United States of America,Canada,5,Shreyas Movva,not out,32,16,2,2,200.00,not out
...,...,...,...,...,...,...,...,...,...,...,...
845,India vs South Africa,South Africa,6,David Miller,c Yadav b Pandya,21,17,1,1,123.52,out
846,India vs South Africa,South Africa,7,Marco Jansen,b Bumrah,2,4,0,0,50.00,out
847,India vs South Africa,South Africa,8,Keshav Maharaj,not out,2,7,0,0,28.57,not out
848,India vs South Africa,South Africa,9,Kagiso Rabada,c Yadav b Pandya,4,3,1,0,133.33,out
849,India vs South Africa,South Africa,10,Anrich Nortje,not out,1,1,0,0,100.00,not out

In [17]:
df_batting.drop(columns="dismissal",inplace=True)
df_batting

,match,team,battingposition,batsmanname,runs,balls,fours,sixes,strikerate,out/not_out
0,Canada vs United States of America,Canada,1,Aaron Johnson,23,16,5,0,143.75,out
1,Canada vs United States of America,Canada,2,Navneet Dhaliwal,61,44,6,3,138.63,out
2,Canada vs United States of America,Canada,3,Pargat Singh,5,7,0,0,71.42,out
3,Canada vs United States of America,Canada,4,Nicholas Kirton,51,31,3,2,164.51,out
4,Canada vs United States of America,Canada,5,Shreyas Movva,32,16,2,2,200.00,not out
...,...,...,...,...,...,...,...,...,...,...
845,India vs South Africa,South Africa,6,David Miller,21,17,1,1,123.52,out
846,India vs South Africa,South Africa,7,Marco Jansen,2,4,0,0,50.00,out
847,India vs South Africa,South Africa,8,Keshav Maharaj,2,7,0,0,28.57,not out
848,India vs South Africa,South Africa,9,Kagiso Rabada,4,3,1,0,133.33,out
849,India vs South Africa,South Africa,10,Anrich Nortje,1,1,0,0,100.00,not out

In [18]:
df_batting['Match_id']=df_batting['match'].map(match_ids_dict)
df_batting

,match,team,battingposition,batsmanname,runs,balls,fours,sixes,strikerate,out/not_out,Match_id
0,Canada vs United States of America,Canada,1,Aaron Johnson,23,16,5,0,143.75,out,T20I # 2632
1,Canada vs United States of America,Canada,2,Navneet Dhaliwal,61,44,6,3,138.63,out,T20I # 2632
2,Canada vs United States of America,Canada,3,Pargat Singh,5,7,0,0,71.42,out,T20I # 2632
3,Canada vs United States of America,Canada,4,Nicholas Kirton,51,31,3,2,164.51,out,T20I # 2632
4,Canada vs United States of America,Canada,5,Shreyas Movva,32,16,2,2,200.00,not out,T20I # 2632
...,...,...,...,...,...,...,...,...,...,...,...
845,India vs South Africa,South Africa,6,David Miller,21,17,1,1,123.52,out,T20I # 2729
846,India vs South Africa,South Africa,7,Marco Jansen,2,4,0,0,50.00,out,T20I # 2729
847,India vs South Africa,South Africa,8,Keshav Maharaj,2,7,0,0,28.57,not out,T20I # 2729
848,India vs South Africa,South Africa,9,Kagiso Rabada,4,3,1,0,133.33,out,T20I # 2729
849,India vs South Africa,South Africa,10,Anrich Nortje,1,1,0,0,100.00,not out,T20I # 2729

In [19]:
df_batting.to_csv('t20 files_summary/fact_batting_summary.csv', index=False)

In [20]:
columns = ["match", "team", "bowlerName", "over", "maiden", "runs", "wickets", "economy", "zeros", "fours", "sixes", "wides", "noballs"]
data = []

for i in range(1415701, 1415756):
    API_KEY = "f9479ced4d7be2f52fc2fe30a1206f67"
    url = f"http://api.scraperapi.com?api_key={API_KEY}&url=https://www.espncricinfo.com/series/icc-men-s-t20-world-cup-2024-1411166/united-states-of-america-vs-canada-1st-match-group-a-{i}/full-scorecard"

    headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36'}
    response = requests.get(url, headers=headers)

    if response.status_code == 200: 
        soup = BeautifulSoup(response.content, "lxml")

        team_names = []
        innings = soup.find_all("div", class_="ds-rounded-lg ds-mt-2")

        for inning in innings:
            team_name_elem = inning.find("span", class_="ds-text-title-xs ds-font-bold ds-capitalize")
            if team_name_elem:
                team_names.append(team_name_elem.text.strip())

        if len(team_names) < 2:
            print(f"ABANDONED MATCH ID {i}")
            continue  

        match_title = f"{team_names[0]} vs {team_names[1]}"

        for idx, inning in enumerate(innings):
            batting_team_elem = inning.find("span", class_="ds-text-title-xs ds-font-bold ds-capitalize")
            if batting_team_elem:
                batting_team = batting_team_elem.text.strip()

                bowling_team = team_names[1] if batting_team == team_names[0] else team_names[0]

            bowling_table = inning.find("table", class_="ds-w-full ds-table ds-table-md ds-table-auto")

            if bowling_table:
                rows = bowling_table.find_all("tr")
                for row in rows:
                    cols = row.find_all("td")
                    if len(cols) >= 11:
                        bowling = cols[0].text.strip()
                        O = cols[1].text.strip()
                        M = cols[2].text.strip()
                        R = cols[3].text.strip()
                        W = cols[4].text.strip()
                        economy = cols[5].text.strip()
                        zeros = cols[6].text.strip()
                        fours = cols[7].text.strip()
                        sixes = cols[8].text.strip()
                        WD = cols[9].text.strip()
                        NB = cols[10].text.strip()
                        
                        
                        data.append([match_title, bowling_team, bowling, O, M, R, W, economy, zeros, fours, sixes, WD, NB])


df_bowling = pd.DataFrame(data, columns=columns)


df_bowling

ABANDONED MATCH ID 1415706
ABANDONED MATCH ID 1415723
ABANDONED MATCH ID 1415730
ABANDONED MATCH ID 1415733

,match,team,bowlerName,over,maiden,runs,wickets,economy,zeros,fours,sixes,wides,noballs
0,Canada vs United States of America,United States of America,Ali Khan,4,0,41,1,10.25,11,5,2,2,0
1,Canada vs United States of America,United States of America,Saurabh Netravalkar,2,0,16,0,8.00,3,2,0,0,0
2,Canada vs United States of America,United States of America,Harmeet Singh,4,0,27,1,6.75,11,3,1,0,0
3,Canada vs United States of America,United States of America,Jasdeep Singh,3,0,24,0,8.00,7,4,0,0,0
4,Canada vs United States of America,United States of America,Shadley van Schalkwyk,3,0,34,0,11.33,1,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,India vs South Africa,India,Jasprit Bumrah,4,0,18,2,4.50,14,2,0,0,0
586,India vs South Africa,India,Axar Patel,4,0,49,1,12.25,8,5,3,2,0
587,India vs South Africa,India,Kuldeep Yadav,4,0,45,0,11.25,6,3,3,0,0
588,India vs South Africa,India,Hardik Pandya,3,0,20,3,6.66,9,1,1,1,1
589,India vs South Africa,India,Ravindra Jadeja,1,0,12,0,12.00,0,0,1,0,0

In [21]:
df_bowling["Match_id"]=df_bowling["match"].map(match_ids_dict)
df_bowling

,match,team,bowlerName,over,maiden,runs,wickets,economy,zeros,fours,sixes,wides,noballs,Match_id
0,Canada vs United States of America,United States of America,Ali Khan,4,0,41,1,10.25,11,5,2,2,0,T20I # 2632
1,Canada vs United States of America,United States of America,Saurabh Netravalkar,2,0,16,0,8.00,3,2,0,0,0,T20I # 2632
2,Canada vs United States of America,United States of America,Harmeet Singh,4,0,27,1,6.75,11,3,1,0,0,T20I # 2632
3,Canada vs United States of America,United States of America,Jasdeep Singh,3,0,24,0,8.00,7,4,0,0,0,T20I # 2632
4,Canada vs United States of America,United States of America,Shadley van Schalkwyk,3,0,34,0,11.33,1,1,2,0,0,T20I # 2632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,India vs South Africa,India,Jasprit Bumrah,4,0,18,2,4.50,14,2,0,0,0,T20I # 2729
586,India vs South Africa,India,Axar Patel,4,0,49,1,12.25,8,5,3,2,0,T20I # 2729
587,India vs South Africa,India,Kuldeep Yadav,4,0,45,0,11.25,6,3,3,0,0,T20I # 2729
588,India vs South Africa,India,Hardik Pandya,3,0,20,3,6.66,9,1,1,1,1,T20I # 2729
589,India vs South Africa,India,Ravindra Jadeja,1,0,12,0,12.00,0,0,1,0,0,T20I # 2729

In [22]:
df_bowling.to_csv("t20 files_summary/fact_bowling_summary.csv",index=False)

In [23]:
columns = ["Playername", "Team", "Image", "Battingstyle", "Bowlingstyle", "Playingrole"]
player_data = []
unique_players = set()
player_profiles = {} 
team_dict = {} 



def clean_text(text):
    text = re.sub(r'[^\x00-\x7F]+', '', text)  
    text = re.sub(r'\(.*?\)', '', text)  
    return text.strip()

for i in range(1415701, 1415756):
    API_KEY = "f9479ced4d7be2f52fc2fe30a1206f67"
    url = f"http://api.scraperapi.com?api_key={API_KEY}&url=https://www.espncricinfo.com/series/icc-men-s-t20-world-cup-2024-1411166/united-states-of-america-vs-canada-1st-match-group-a-{i}/full-scorecard"
    headers= {"User-Agent": "Chrome/120.0.0.0 Safari/537.36"}
    response = requests.get(url,headers)

    if response.status_code == 200:
        response.encoding = 'utf-8'
        soup = BeautifulSoup(response.content, "html.parser")

       
        innings = soup.find_all("div", class_='ds-rounded-lg ds-mt-2')
        
        
        for index, inning in enumerate(innings):
            team_name = inning.find("span", class_="ds-text-title-xs ds-font-bold ds-capitalize")
            if team_name:
                team_name = team_name.text.strip()
                team_dict[index] = team_name

        
        for index, inning in enumerate(innings):
            team_name = team_dict.get(index, "Unknown Team")  

            
            batting_table = inning.find("table", class_="ds-w-full ds-table ds-table-md ds-table-auto ci-scorecard-table")
            if batting_table:
                for row in batting_table.find_all("tr"):
                    cols = row.find_all("td")
                    if len(cols) >= 7:
                        player_name = clean_text(cols[0].text.strip())

                        if player_name in unique_players:
                            continue 
                        unique_players.add(player_name)

                       
                        player_link_tag = cols[0].find("a")
                        if player_link_tag:
                            player_profile_url = "https://www.espncricinfo.com" + player_link_tag["href"]
                            og_url=player_profile_url = f"http://api.scraperapi.com?api_key={API_KEY}&url={player_profile_url}"


                            
                            if player_name not in player_profiles:
                                player_response = requests.get(og_url)
                                if player_response.status_code == 200:
                                    player_response.encoding = 'utf-8'
                                    player_soup = BeautifulSoup(player_response.content, "html.parser")

                                  
                                    image_tag = player_soup.find("img", alt=lambda x: x and player_name in x)
                                    image_url = image_tag['src'] if image_tag else "N/A"

                                    batting_style_p = player_soup.find("p", string="Batting Style")
                                    batting_style = batting_style_p.find_next("p").text.strip() if batting_style_p else "N/A"

                                    bowling_style_p = player_soup.find("p", string="Bowling Style")
                                    bowling_style = bowling_style_p.find_next("p").text.strip() if bowling_style_p else "N/A"

                                    playing_role_p = player_soup.find("p", string="Playing Role")
                                    playing_role = playing_role_p.find_next("p").text.strip() if playing_role_p else "N/A"

                                    player_profiles[player_name] = [player_name, team_name, image_url, batting_style, bowling_style, playing_role]

                            player_data.append(player_profiles[player_name])

       
        for index, inning in enumerate(innings):
            bowling_team = team_dict.get(1 - index, "Unknown Team")  
            if bowling_team == "Unknown Team":
                print(f"Warning: team_dict does not contain key {1 - index}, check team assignment.")

            bowling_table = inning.find("table", class_="ds-w-full ds-table ds-table-md ds-table-auto")
            if bowling_table:
                for row in bowling_table.find_all("tr"):
                    cols = row.find_all("td")
                    if len(cols) >= 2:
                        player_name = clean_text(cols[0].text.strip())

                        if player_name in unique_players:
                            continue  
                        unique_players.add(player_name)

                        player_link_tag = cols[0].find("a")
                        if player_link_tag:
                            player_profile_url = "https://www.espncricinfo.com" + player_link_tag["href"]
                            og_url=player_profile_url = f"http://api.scraperapi.com?api_key={API_KEY}&url={player_profile_url}"

                            if player_name not in player_profiles:
                                player_response = requests.get(og_url)
                                if player_response.status_code == 200:
                                    player_response.encoding = 'utf-8'
                                    player_soup = BeautifulSoup(player_response.content, "html.parser")

                                    image_tag = player_soup.find("img", alt=lambda x: x and player_name in x)
                                    image_url = image_tag['src'] if image_tag else "N/A"

                                    batting_style_p = player_soup.find("p", string="Batting Style")
                                    batting_style = batting_style_p.find_next("p").text.strip() if batting_style_p else "N/A"

                                    bowling_style_p = player_soup.find("p", string="Bowling Style")
                                    bowling_style = bowling_style_p.find_next("p").text.strip() if bowling_style_p else "N/A"

                                    playing_role_p = player_soup.find("p", string="Playing Role")
                                    playing_role = playing_role_p.find_next("p").text.strip() if playing_role_p else "N/A"

                                    player_profiles[player_name] = [player_name, bowling_team, image_url, batting_style, bowling_style, playing_role]

                            player_data.append(player_profiles[player_name])

df_players1 = pd.DataFrame(player_data, columns=columns)


df_players1

,Playername,Team,Image,Battingstyle,Bowlingstyle,Playingrole
0,Aaron Johnson,Canada,"https://img1.hscicdn.com/image/upload/f_auto,t...",Right hand Bat,Right arm Offbreak,Batter
1,Navneet Dhaliwal,Canada,"https://img1.hscicdn.com/image/upload/f_auto,t...",Right hand Bat,Right arm Medium fast,Middle order Batter
2,Pargat Singh,Canada,"https://img1.hscicdn.com/image/upload/f_auto,t...",Right hand Bat,Right arm Offbreak,Allrounder
3,Nicholas Kirton,Canada,"https://img1.hscicdn.com/image/upload/f_auto,t...",Left hand Bat,N/A,Batting Allrounder
4,Shreyas Movva,Canada,"https://img1.hscicdn.com/image/upload/f_auto,t...",Right hand Bat,N/A,Wicketkeeper Batter
...,...,...,...,...,...,...
260,Kuldeep Yadav,India,"https://img1.hscicdn.com/image/upload/f_auto,t...",Left hand Bat,Left arm Wrist spin,Bowler
261,Mahedi Hasan,Bangladesh,"https://img1.hscicdn.com/image/upload/f_auto,t...",Right hand Bat,Right arm Offbreak,Allrounder
262,Milind Kumar,United States of America,"https://img1.hscicdn.com/image/upload/f_auto,t...",Right hand Bat,Right arm Offbreak,Allrounder
263,Kyle Mayers,West Indies,"https://img1.hscicdn.com/image/upload/f_auto,t...",Left hand Bat,Right arm Medium,Batting Allrounder
264,Nangeyalia Kharote,Afghanistan,"https://img1.hscicdn.com/image/upload/f_auto,t...",Left hand Bat,Slow Left arm Orthodox,Allrounder

In [24]:
df_players1.to_csv('t20 files_summary/dim_players_summary.csv', index=False)